; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27043.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\mau_l\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
